### ISSUE TITLE
Update README For Updates in Classifier

### ISSUE THREAD

**Issue by CavRiley** [BRAINSia/dcm-classifier#37]
**Documentation Location**

The documentation issue is located in the README file of the project repository.

**Type of Documentation Issue**

This is an enhancement request to improve the clarity and completeness of the README documentation.

**Issue Description**

The current README lacks detailed instructions on how to install and use the package effectively. Additionally, it does not provide information on the prerequisites required for running the package.

**Suggested Changes**

* Add a comprehensive installation guide with clear steps for installing the package via pip.
* Include instructions on how to import and use the package in various environments.
* Provide details on any dependencies or system requirements necessary for running the package.
* Incorporate examples or code snippets to illustrate common usage scenarios.

**Additional Context**

The current README provides a basic overview of the project but lacks sufficient information for users to effectively utilize the package. Enhancing the documentation will improve the user experience and reduce confusion for new users.

**Proposed Solution**

To address this issue, I propose updating the README with detailed installation instructions, usage guidelines, and information on prerequisites. Additionally, including examples and troubleshooting tips will further enhance the usability of the documentation.

**Additional Comments**

Improving the README documentation is crucial for ensuring that users can easily understand and utilize the features offered by the package. Clear and concise instructions will help users get started quickly and minimize the need for additional support.

**Comment by mbrzus** [comment]
The paper was published a few days ago:

Include the link to the paper: 
https://www.spiedigitallibrary.org/conference-proceedings-of-spie/12931/3006568/DICOM-sequence-selection-for-medical-imaging-applications/10.1117/12.3006568.full#_=_

And include instruction on how to cite it. Look up the ways on github to add citation information for easy way.
We might want to provide not only the text for citation:
[Michal Brzus](https://www.spiedigitallibrary.org/profile/Michal.Brzus-4339246), [Cavan J. Riley](https://www.spiedigitallibrary.org/profile/Cavan.Riley-5066963), Joel Bruss, [Aaron Boes](https://www.spiedigitallibrary.org/profile/Aaron.Boes-5021766), [Randall Jones](https://www.spiedigitallibrary.org/profile/Randall.Jones-5021770), and Hans J. Johnson "DICOM sequence selection for medical imaging applications", Proc. SPIE 12931, Medical Imaging 2024: Imaging Informatics for Healthcare, Research, and Applications, 1293108 (2 April 2024); https://doi.org/10.1117/12.3006568

But also citation fiels such as *.bib etc
