### ISSUE TITLE
missing metadata for training/testing datasets 

### ISSUE THREAD

**Issue by deepakri201** [BRAINSia/dcm-classifier#67]
Hi, 

I've been trying out your toolbox for modality classification. 

However, I noticed that in your publication, there is limited information provided about the datasets - for instance which collections, which institutions, manufacturers, etc. 

I am particularly interested in using your model for prostate MR modality classification -- and this information would be very helpful to make sure my testing data does not overlap with your model's training data. 

Thank you,
Deepa

**Comment by hjmjohnson** [comment]
We used many public and private datasets in both Prostate and Neurologic domains in creating this tool.

We have GE, Siemens, and Phillips data represented at both 1.5 and 3T.  There are other manufacturers as well, but those would be in very small quantities.

**Comment by deepakri201** [comment]
Thank you for your quick response. 

Would it be possible to provide the exact collection names used, at least for the prostate? To provide some context, I am working with datasets from Imaging Data Commons (https://portal.imaging.datacommons.cancer.gov/) and TCIA. 

It would be extremely beneficial to know if the datasets used for training your model overlapped with ones in IDC/TCIA, including: ProstateX, QIN-Prostate-Repeatability, Prostate3T, Prostate-Diagnosis, ProstateMRI, Prostate-MRI-Fused-Pathology and Prostate-MRI-US-Biopsy. 

Thank you again for your time.

**Comment by hjmjohnson** [comment]
@deepakri201 Sorry, no. we do not have the bandwidth to get an accurate listing.  I will send an email to those who worked on this project, but I am not optimistic that we can get the exact datasets.  

Much of the data was not public domain.    

I can confirm that the training and validation data sets do overlap with the public datasets that you list.    An undergraduate student was tasked with finding as many exemplars as possible in both neuro-degeneration and prostate data sets.

**Comment by deepakri201** [comment]
I understand, thank you!
